/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CreateSessionPopup: typeof import('./components/admin/session/CreateSessionPopup.vue')['default']
    CreateSongPopup: typeof import('./components/admin/song/CreateSongPopup.vue')['default']
    Download: typeof import('./components/admin/Download.vue')['default']
    LeftLandingCard: typeof import('./components/dashboard/left-card/LeftLandingCard.vue')['default']
    LoginCard: typeof import('./components/LoginCard.vue')['default']
    PendingSong: typeof import('./components/admin/pending-song/PendingSong.vue')['default']
    PendingSongList: typeof import('./components/admin/pending-song/PendingSongList.vue')['default']
    PlaySong: typeof import('./components/dashboard/right-card/song-selection/PlaySong.vue')['default']
    PreviousWinner: typeof import('./components/dashboard/right-card/PreviousWinner.vue')['default']
    RegisterCard: typeof import('./components/RegisterCard.vue')['default']
    RightLandingCard: typeof import('./components/dashboard/right-card/RightLandingCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Session: typeof import('./components/admin/session/Session.vue')['default']
    SessionList: typeof import('./components/admin/session/SessionList.vue')['default']
    Snipper: typeof import('./components/snipper/snipper.vue')['default']
    SnipperPanel: typeof import('./components/snipper/SnipperPanel.vue')['default']
    Song: typeof import('./components/admin/song/Song.vue')['default']
    SongList: typeof import('./components/admin/song/SongList.vue')['default']
    SongSelection: typeof import('./components/dashboard/right-card/song-selection/SongSelection.vue')['default']
    SongSelectionList: typeof import('./components/dashboard/right-card/SongSelectionList.vue')['default']
    SongUpload: typeof import('./components/dashboard/left-card/SongUpload.vue')['default']
    SongVote: typeof import('./components/dashboard/left-card/SongVote.vue')['default']
    SongVoteList: typeof import('./components/dashboard/left-card/SongVoteList.vue')['default']
    Toast: typeof import('./components/common/Toast.vue')['default']
    UpdateSessionPopup: typeof import('./components/admin/session/UpdateSessionPopup.vue')['default']
    UpdateSongPopup: typeof import('./components/admin/song/UpdateSongPopup.vue')['default']
    UpdateUserPopup: typeof import('./components/admin/user/UpdateUserPopup.vue')['default']
    UploadInput: typeof import('./components/dashboard/left-card/UploadInput.vue')['default']
    User: typeof import('./components/admin/user/User.vue')['default']
    UserList: typeof import('./components/admin/user/UserList.vue')['default']
    ViewSessionSongsPopup: typeof import('./components/admin/session/ViewSessionSongsPopup.vue')['default']
    VoteSong: typeof import('./components/dashboard/right-card/song-selection/VoteSong.vue')['default']
    WelcomeSign: typeof import('./components/dashboard/WelcomeSign.vue')['default']
  }
}
